version: "3"
services:
  postgres:
    container_name: postgres-container
    image: postgres:latest
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - "35432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: verx_development
    networks:
      - my-networks
  api:
    container_name: api-container
    image: node:12
    working_dir: /usr/src/app
    restart: always
    command: bash -c "npm install --only=prod && npm run start"
    volumes:
      - ./dist/:/usr/src/app/dist/
      - ./package.json:/usr/src/app/package.json
    ports:
      - "3000:3000"
    links:
      - postgres
    networks:
      - my-networks
    environment:
      DB_HOST: postgres
    
networks:
  my-networks:
    driver: bridge
